#
# DESIGN CONFIGURATION
#
# Settings apply to this design only. For email settings, see the
# `emailConfig.yaml` file in each individual email directory. For overall
# settings, see the `premail.yaml` file in your project's home directory.
#

# SYNTAX NOTES
#
# Values that include CSS-reserved selectors such as periods, commas, slashes or
# colons will error unless they are quoted twice, "'Like this.'" An example is
# the custom font URL. More information:
# https://github.com/pmowrer/node-sass-json-importer#importing-strings
#
# Any values that include the pound sign (#), such as hexidecimal color values,
# need to be single-quoted, '#Likethis'.
#
# Color values:
# Use CSS color keywords, RGB format, or hex format. You can use either 3- or
# 6-digit hex values; MJML will automatically convert them. Do not use RGBA.
# Also note that some email clients will attempt to invert colors when the user
# has set a preference for dark mode. You have limited control over what these
# inverted colors will be, though workarounds exist. Resources:
# https://www.litmus.com/blog/background-colors-html-email/
# https://www.hteumeuleu.com/2021/fixing-gmail-dark-mode-css-blend-modes/
#
# Size values:
# MJML only supports sizes set in pixels. This is largely due to the wide
# variety in email client interpretation of values such as "1em", which can
# range from 12px to 17px. Resources:
# https://us4.campaign-archive.com/?u=00194e641f365c79871912856&id=1b0c8bc3ba&e=d274356b59
# https://email.uplers.com/blog/em-or-px-how-to-code-your-emails-right/

# DIRECTORY SETTINGS
# If set, these design directory settings override the project-wide settings
# in `premail.yaml` in your home project directory.
#
# These design directory settings can subsequently be overridden by an email's
# directory settings in a `emailConfig.yaml` file.
dirs:
  theme:
  # Subdirectory of this design where styles are kept
  # dir: theme

  output:
    # When test-building this design, save files to this subdirectory
    # dir: dist

# TEMPLATE SETTINGS
templates:
  # Filename of the main template file in this design.
  main: index.hbs

# PAGE SETTINGS
page:
  # center: If you want your email to be aligned to the default for your
  # language (left-aligned, for LTR languages like English), set this to false.
  # Note that this may break some advanced aspects of MJML like background
  # images, so use with care. Details:
  # https://github.com/mjmlio/mjml/issues/2283#issuecomment-863021249
  center: true
  # backgroundImage: Note that this must point to an Internet-accessible image
  # (not a local file). It will be repeated across the background of the email.
  # Be sure to double-quote the URI, as in the example provided.
  # backgroundImage: "'https://www.toptal.com/designers/subtlepatterns/patterns/moroccan-flower.png'"
  # backgroundColor: Background color for the overall email, and fallback if
  # a background image is set but a client refuses to load it. See "Color
  # values" at the top of this document.
  backgroundColor: '#fff'

# SECTION SETTINGS
sections:
  # main: Settings here will apply to the following sections, if they exist:
  # - salutation
  # - body
  # - signoff
  main:
    # backgroundColor: See "Color values" at the top of this document.
    backgroundColor: '#fff'
    # horizontalPadding: See "Size values" at the top of this document.
    horizontalPadding: 18px

  salutation:
    # padding: See "Size values" at the top of this document.
    padding:
      top: 18px
      bottom: 0px

  body:
    # padding: See "Size values" at the top of this document.
    padding:
      top: 0px
      bottom: 0px

  signoff:
    # padding: See "Size values" at the top of this document.
    padding:
      top: 0px
      bottom: 18px

  topNav:

  banner:

  social:
    # backgroundColor: See "Color values" at the top of this document.
    backgroundColor: '#fff'
    # horizontalPadding: See "Size values" at the top of this document.
    horizontalPadding: 0px
    # verticalPadding: See "Size values" at the top of this document.
    verticalPadding: 0px
    # topBorder: Appears between the social icons and email content.
    topBorder:
      # include: Set to false to omit the border.
      include: true
      # verticalPadding: See "Size values" at the top of this document.
      verticalPadding: 0px
      # borderWidth: See "Size values" at the top of this document.
      borderWidth: 1px
      # borderStyle: Any valid CSS border-style value may be used.
      borderStyle: dashed

  bottomNav:

  footer:
    # backgroundColor: See "Color values" at the top of this document.
    backgroundColor: '#fff'
    # horizontalPadding: See "Size values" at the top of this document.
    horizontalPadding: 18px
    # verticalPadding: See "Size values" at the top of this document.
    verticalPadding: 18px

# COLOR BRANDING
# See "Color values" at the top of this document.
colors:
  # primary: Color for buttons, navigation menus, and social media icons.
  primary: '#800080'
  # secondary: Color for headline text.
  secondary: '#666f9f'

# FONT SETTINGS
fonts:
  stack:
    # Base options:
    #   'sans'
    #   'serif'
    #   'mono'
    #
    # Sets a base font stack of safe fonts (sans-serif, serif, or monospaced,
    # respectively), for every OS and device. These will look
    # similar, though not identical, across email systems. For more information
    # about this approach, see:
    # https://markdotto.com/2018/02/07/github-system-fonts/#the-stack
    # https://www.digitalocean.com/community/tutorials/css-system-font-stack
    # https://css-tricks.com/snippets/css/system-font-stack/
    # https://whistlr.info/2020/system-font/
    # https://systemfontstack.com
    #
    # If you don't enable 'google' or 'custom', below, these will be the only
    # fonts used.
    base: sans

    google:
      # google: If enabled, choose a Google font and options, and this will
      # automatically embed the font in a best-practice tag. Note that web fonts
      # require an additional download (potentially slowing down loading) and
      # are only visible in a small number of email systems, so most people will
      # be seeing the base font set above. For more information about this
      # approach, see:
      # https://www.litmus.com/blog/the-ultimate-guide-to-web-fonts/
      # https://css-tricks.com/kinda-can-use-custom-fonts-html-emails/
      enabled: true
      # name: The name of the Google Font. Capitalization and spaces count!
      name: Source Sans Pro
      # weights: The font weight(s) you want to use (enter in ascending order):
      weights:
        - 400
        - 900
      # italics: Whether to include an italic variant for each weight
      italics: true

    custom:
      # custom: If enabled, choose a non-Google web font, or use an
      # already-crafted URI pointing to a font-loading CSS file.
      enabled: false
      # name: The name of your custom font
      name: Example Custom Font
      # href: Valid URI pointing to a CSS file that loads web font(s). For an
      # example, here's Google Fonts' file for Sans Serif Pro:
      # https://fonts.googleapis.com/css2?family=Source+Sans+Pro&amp;display=swap
      # You'll probably want to include references to bold and italics variants
      # as well. Be sure to double-quote the URI, as in the example provided.
      href: "'https://example.com/font.css'"

# TEXT STYLES
text:
  # default: Styles for body text, when not otherwise styled.
  default:
    # color: See "Color values" at the top of this document.
    color: '#666'
    # size: See "Size values" at the top of this document.
    size: 18px
    # lineHeight: As in CSS, set to unitless values that multiply the font
    # size. For instance, if your default font size is 18px, a line-height of
    # 1 would set it to 18px as well; a setting of 1.5 would set it to 27px.
    lineHeight: '1.8'
    # verticalPadding: If unset, this will be equal to the font size.
    verticalPadding:

# INLINE LINK STYLES
# These styles do not affect buttons or navigation item links.
links:
  # color: By default links will use "primary" from "Color Branding", above.
  # Set this value to override that color. See "Color values" at the top of this
  # document.
  color:
  # weight: Any valid CSS font-weight value may be used.
  weight: bold
  # decoration: Any valid CSS text-decoration value may be used.
  decoration: underline

# LIST STYLES
# These styles only apply to lists created with the <mj-list> and <mj-li>
# components (see README). They can be overridden by individual component
# settings.
lists:
  # leftPadding: The default amount by which lists will be padded from the left
  # margin. If you set this to 0, the bullets in the list may overflow their
  # containers.
  leftPadding: 25px
  # listBottomPadding: To match paragraph styles, set this to the same value as
  # text.default.verticalPadding or text.default.size.
  listBottomPadding: 18px
  # itemBottomPadding: If not set, this will match listBottomPadding.
  itemBottomPadding:
  # fontSize: If not set, this will match text.default.size.
  fontSize:
  # lineHeight: If not set, this will match text.default.lineHeight.
  lineHeight:

# BUTTON STYLES
# To learn about MJML's button settings, see:
# https://documentation.mjml.io/#mj-button
# Be sure to use both the mj-class and css-class attributes as specified.
buttons:
  # primary: Use mj-class="button" css-class="button"
  primary:
    # height: Explicitly set the button's height. If unset, the button will
    # be large enough to contain its content (text and padding). See "Size
    # values" at the top of this document.
    height:
    # width: Explicitly set the button's width. If unset, the button will
    # be large enough to contain its content (text and padding). Note this can
    # cause the button to overflow its container! See "Size values" at the top
    # of this document.
    width:
    # align: Horizontal alignment of the button itself.
    # Valid values: left/right/center
    align: center
    # buttonPadding: The padding between the button and surrounding content.
    # See "Size values" at the top of this document.
    buttonPadding:
      top: 9px
      bottom: 27px
      left: 18px
      right: 18px
    # contentPadding: The padding inside the button itself, around the text.
    # Value is a string in the form "vertical horizontal", e.g. "10px 5px" or
    # "top right bottom left", e.g. "0px 10px 20px 10px". Also see "Size values"
    # at the top of this document.
    contentPadding: 9px 36px
    # cornerRadius: See "Size values" at the top of this document.
    cornerRadius: 9px
    # backgroundColor: By default this will use "primary" from "Color Branding"
    # above. Set this value to override that color. See "Color values" at the
    # top of this document.
    backgroundColor:
    # textColor: See "Color values" at the top of this document.
    textColor: '#fff'
    # weight: Any valid CSS font-weight value may be used.
    weight: bold
    # style: Any valid CSS font-style value may be used.
    style: normal
    # decoration: underline/overline/none
    decoration: none
    # textSize: See "Size values" at the top of this document.
    textSize: 22px
    # lineHeight: As in CSS, set to unitless values that multiply the font
    # size. For instance, if your default font size is 18px, a line-height of
    # 1 would set it to 18px as well; a setting of 1.5 would set it to 27px.
    # Only apparent in multi-line buttons.
    lineHeight: '1'

  # secondary: Use both
  # mj-class="button button--secondary" css-class="button button--secondary"
  # for inheritance of styles from the primary button. You can also use only
  # mj-class="button--secondary" css-class="button--secondary"
  # but note that it will still inherit some MJML button default properties.
  secondary:
    height:
    width:
    align:
    buttonPadding:
      top:
      bottom:
      left:
      right:
    contentPadding:
    cornerRadius:
    # backgroundColor: By default this will use "secondary" from "Color Branding"
    # above. Set this value to override that color.
    backgroundColor:
    textColor:
    weight:
    style:
    decoration:
    textSize:
    lineHeight:

  # ghost: The default style of the ghost button simply inverts the colors of
  # the primary button. Use both
  # mj-class="button button--ghost" css-class="button button--ghost"
  # for inheritance of styles from the primary button. You can also use only
  # mj-class="button--ghost" css-class="button--ghost"
  # but note that it will still inherit some MJML button default properties.
  ghost:
    height:
    width:
    align:
    buttonPadding:
      top:
      bottom:
      left:
      right:
    contentPadding:
    cornerRadius:
    borderColor:
    # borderWidth: See "Size values" at the top of this document.
    borderWidth: 2px
    # borderStyle: Any valid CSS border-style value may be used.
    borderStyle: solid
    backgroundColor:
    textColor:
    weight:
    style:
    decoration:
    textSize:
    lineHeight:

# SIGNOFF STYLES
# These styles only apply to the <mj-signoff> component (see README).
signoff:
  # lineHeight: Applies to all text elements in the sign-off. You will probably
  # want to set this to '1' so that the top of the text aligns with the image.
  lineHeight: '1'
  # closingBottomPadding: If not set, this will match
  # text.default.verticalPadding (if set) or text.default.size.
  closingBottomPadding:
  # nameBottomPadding: If not set, this will match
  # text.default.verticalPadding (if set) or text.default.size.
  nameBottomPadding: 0
  # titleBottomPadding: If not set, this will match
  # text.default.verticalPadding (if set) or text.default.size.
  titleBottomPadding: 0
  # title2BottomPadding: If not set, this will match
  # text.default.verticalPadding (if set) or text.default.size.
  title2BottomPadding: 0
  # title3BottomPadding: If not set, this will match
  # text.default.verticalPadding (if set) or text.default.size.
  title3BottomPadding: 0

# TYPOGRAPHY
# These settings apply to both your HTML version and (if generating) your
# plain-text version.
typography:
  # convertQuoteAndApostrophe: Replaces instances of straight quotes and
  # apostrophes (actually tick marks) with their curly equivalents.
  convertQuoteAndApostrophe: true
  # convertDash: Replaces instances of em-dashes and en-dashes, with their
  # true typographical equivalents.
  convertDash: true
  # convertEllip: Replaces instances of three dots (...) with the HTML
  # ellipsis character.
  convertEllip: true
  # opticallyAlignLetters: For certain letters, pull or push them to optically
  # align with the margins. See
  # https://en.wikipedia.org/wiki/Optical_margin_alignment
  opticallyAlignLetters: true
  # enableSmallCaps: When an acronym or initialism is encountered, it will be
  # rendered in small-caps instead of regular-height caps. Uses the CSS
  # font-variant property, which is respected in most email clients, and falls
  # back to regular-height caps when it isn't. See
  # https://en.wikipedia.org/wiki/Small_caps
  enableSmallCaps: true

# ACCESSIBILITY
a11y:
  # enforceImageAlt: When set to true, image tags will be required to have "alt"
  # tags -- empty tags are valid -- and they will conform to accessibility and
  # HTML guidelines. Alt tags are important for recipients who have images
  # turned off (including, by default, all Gmail users), screen readers, and
  # deliverability.
  #
  # An image that has no alt text defined will be given an empty alt tag, which
  # is the correct method for images that are purely decorative. Because of
  # this, do not use this as a mechanism to catch empty alt text when it should
  # be present, because in the case of decorative images empty alt text is
  # correct.
  #
  # Resources:
  # https://davidwalsh.name/accessibility-tip-empty-alt-attributes
  # https://www.w3.org/WAI/tutorials/images/decorative/
  # https://accessibleweb.com/question-answer/when-should-i-use-a-null-or-empty-alt-tag/
  # https://support.siteimprove.com/hc/en-gb/articles/115000013031-Accessibility-Image-Alt-text-best-practices
  #
  # For more information about the filters applied using this tool, see
  # https://codsen.com/os/html-img-alt
  enforceImageAlt: true

# CUSTOM HEAD ELEMENTS
# HTML is inserted verbatim into the <head> of the email document. Use the
# optional "description" element to describe the reason for the HTML.
head:
  # - html: <meta name="example" content="example" />
  #   description: An example.
  # - html: <meta name="Generator" content="Microsoft Word 15 (filtered medium)" />
  #   description: Necessary for custom list markers. See https://www.litmus.com/blog/the-ultimate-guide-to-bulleted-lists-in-html-email/

# PREVIEW TEXT PADDING
# When set to true, appends spaces to the preview or preheader text you enter to
# ensure that the rest of the content of your email isn't pulled up into the
# preview. See:
# https://www.goodemailcode.com/email-code/preheader
previewPad: true
