---
printWidth: 80
trailingComma: es5
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
bracketSpacing: true
proseWrap: always # Tell Prettier to wrap Markdown files at the printWidth.

# Because our templates are a mix of Handlebars and MJML, and because
# Prettier doesn't process Handlebars includes correctly, we use regular ol'
# HTML standards to format the files.
#
# References:
# https://github.com/prettier/prettier/pull/10290
# https://github.com/ember-template-lint/ember-template-lint/issues/486
# https://github.com/prettier/prettier/issues/10707
overrides:
  - files:
      - '*.html'
      - '*.mjml'
      - '*.hbs'

    # Source for these options:
    # https://github.com/ikatyang/angular-html-parser/tree/master/packages/angular-html-parser#api
    options:
      parser: html
      htmlWhitespaceSensitivity: strict
      canSelfClose: true
      html:
        void: any
