#
# QUICKSTART CONFIGURATION
#
# This file is formatted in YAML -- indentation and whitespace is important!
#
# If you're not familiar with YAML, there are lots of guides and many
# implementations out there. Here are some examples:
# https://blog.stackpath.com/yaml/
# https://www.codeproject.com/Articles/1214409/Learn-YAML-in-five-minutes
# https://yaml.org

# 1. Folders
folders:

  design:

    # Name of the folder for designs
    name: designs

    # If no design is specified, default to this directory
    default: _templates

  theme:

    # Subdirectory of designs in which settings for styling are kept
    dir: theme

  email:

    # Name of the folder for individual emails
    name: emails

  output:

    # Subdirectory of emails in which to export HTML code
    dir: dist

# 2. Files and file types
files:

  # Main template file
  template: index.tpl

  mjml:

    # File extensions to process from MJML to HTML
    ext: tpl

# 3. Options
text:

  # Whether or not to generate a plain-text version. The subsequent options only
  # apply if this is set to "true".
  generate: true

  # Whether to include the following elements in the plain-text version.
  include:
    topNav:     true
    banner:     true
    salutation: true
    signoff:    true
    social:     true
    bottomNav:  true
    footer:     true
