#
# QUICKSTART CONFIGURATION
#
# This file is formatted in YAML -- indentation and whitespace is important!
#
# If you're not familiar with YAML, there are lots of guides and many
# implementations out there. Here are some examples:
# https://blog.stackpath.com/yaml/
# https://www.codeproject.com/Articles/1214409/Learn-YAML-in-five-minutes
# https://yaml.org
#
# tl;dr: You can edit things on the right side of colons (:) but not on the
# left. Don't change the indentation or spacing.
#
# For design configuration, see themeConfig.yaml inside individual design
# directories.
#

# 1. Folders
folders:
  design:
    # Name of the folder for designs
    name: designs

    # If no design is specified, default to this directory
    default: _templates

  theme:
    # Subdirectory of designs in which settings for styling are kept
    dir: theme

  email:
    # Name of the folder for individual emails
    name: emails

  output:
    # Subdirectory of emails in which to export HTML code
    dir: dist

# 2. Files and file types
files:
  # Name of the main template file
  template: index.hbs

# @TODO: This should really go in an email-specific config file.
# 3. Email-building options
text:
  # Whether or not to generate a plain-text version. The subsequent options only
  # apply if this is set to "true". Note that while only a small portion of
  # recipients will see the text version, it appears to lower the risk of your
  # email being interpreted as spam. Resources:
  # https://www.litmus.com/blog/best-practices-for-plain-text-emails-a-look-at-why-theyre-important/
  # https://www.indiehackers.com/post/10-tips-for-better-email-deliverability-0f73b1fbee
  generate: true

  # When set to true, images are replaced by URLs to the image file in the
  # plaintext version. Set to false to omit these images completely. Any tags
  # wrapping the images (such as link tags) will be unaffected.
  images: false

  # Whether to include the following elements in the plain-text version.
  include:
    topNav: true
    banner: true
    salutation: true
    body: true
    signoff: true
    social: true
    bottomNav: true
    footer: true

# 3. Language
language:
  # Sets the default language wrapping each email. This must be set to a valid
  # lanugage tag to inform assistive devices like screen readers. If you have
  # multilingual emails, you can include `lang` attributes in wrapping <div>
  # tags. Resources:
  # https://github.com/hteumeuleu/email-guidelines#lang
  # https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
  default: en

# 4. Fine-grained detail settings
details:
  # Typography settings apply to both your HTML version and (if generating) your
  # plain-text version.
  typography:
    # improveQuoteAndApostrophe: Replaces instances of straight quotes and
    # apostrophes (actually tick marks) with their curly equivalents.
    improveQuoteAndApostrophe: true
    # improveDashAndEllip: Replaces instances of em-dashes, en-dashes, and
    # ellipses with their true typographical equivalents. For details, see
    # https://github.com/davidmerfield/Typeset/blob/master/src/punctuation.js
    improveDashAndEllip: true
    # hangPunctuation: When punctuation (such as quotes) begins a line, move
    # them beyond the margin so that the first letter aligns with the margin.
    # See https://en.wikipedia.org/wiki/Hanging_punctuation
    hangPunctuation: true
    # opticallyAlignLetters: For certain letters, pull or push them to optically
    # align with the margins. See
    # https://en.wikipedia.org/wiki/Optical_margin_alignment
    opticallyAlignLetters: true
    # enableSmallCaps: When an acronym or initialism is encountered, it will be
    # rendered in small-caps instead of regular-height caps. Uses the CSS
    # font-variant property, which is respected in most email clients, and falls
    # back to regular-height caps when it isn't. See
    # https://en.wikipedia.org/wiki/Small_caps
    enableSmallCaps: true
    # removeWidows: Technically, a widow is a single line "left over" on a
    # paragraph that's been wrapped to another column. But on the web, where
    # columns are less common, "widow" more often refers to a single word
    # wrapped onto a line by itself. This tool inserts a non-breaking space
    # between the last two words in a paragraph to ensure that at least two
    # words will appear on a line. See
    # https://codsen.com/os/string-remove-widows
    removeWidows: true

  # previewPad: When set to true, appends spaces to the preview or preheader
  # text you enter to ensure that the rest of the content of your email isn't
  # pulled up into the preview. Resources:
  # https://www.goodemailcode.com/email-code/preheader
  previewPad: true
