name: Feature Request
description: Suggest an idea for Premail
title: 'feat: '
labels: 'Type: Feature'
assignees: ''
# # Feature Request

# ## Type of feature

# - [ ] New functionality
# - [ ] Performance
# - [ ] Code refactoring (e.g. to be simpler or easier to understand)
# - [ ] Developer Experience (DX)
# - [ ] Other (please describe):

# ## Describe the feature

# <!-- A clear and concise description of your feature request. Please note if your request is related to a problem. -->

# ## Describe preferred solution

# <!-- A clear and concise description of what you want to happen. -->

# ## Describe alternatives

# <!-- A clear and concise description of any alternative solutions or features you've considered. -->

# ## Related code

# <!-- If you are able to illustrate this request with an example, please provide it here. -->

# ## Additional context

# <!-- List any other information that is relevant to your issue. Use cases, screenshots, related issues, stack traces, links to relevant information, environment information if applicable, etc. -->

# **If the feature request is approved, would you be willing to submit a PR?**
# _(Help can be provided if you need assistance submitting a PR)_

# - [ ] Yes
# - [ ] No
