name: Support question
description: Ask a question about how to use Premail
labels: 'Type: Question'
body:
  - type: markdown
    attributes:
      value: |
        **Before you ask a question, be sure you've checked the [Premail documentation](https://premail.dev) -- your question may already be answered there!**
  - type: input
    id: version
    attributes:
      label: Premail version
      description: 'Run `premail -v` and paste the output here.'
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: On what operating system are you running Premail?
      options:
        - Linux
        - Mac
        - Windows
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true
