name: Support Question
description: Ask a question about how to use Premail
title: 'support: '
labels: 'Type: Question'
body:
  - type: input
    id: version
    attributes:
      label: Premail version
      description: 'Run `premail -v` and paste the output here.'
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true
