name: Build
description: Change the build process for Premail
title: 'build: '
labels: 'Type: Build'
body:
  - type: markdown
    attributes:
      value: |
        **This issue type is intended for changes to Premail's own internal build processes, for instance GitHub Actions.**
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
