name: Build
description: Change the build process for Premail
body:
  - type: markdown
    attributes:
      value: |
        This issue type is intended for changes to Premail's own internal build processes, for instance the GitHub Actions.
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
