# Settings corresponding to the "Details" section of config.yaml.
details:
  # Default typographic enhancement configuration
  typography:
    detergent:
      options:
        useXHTML: false
        removeLineBreaks: true
        stripHtml: false
        removeWidows: false # Introduces issues with CSS code
        convertDashes: true
        convertApostrophes: true
        convertDotsToEllipsis: true
    typeset:
      options:
        hyphenate: false # Generates too many edge cases
        ligatures: false # Unreliable
        punctuation: false # Handled by Detergent
        quotes: false # Handled by Detergent
        spaces: false # Unnecessary
        hangingPunctuation: true
        smallCaps: true
      css: # Settings requiring CSS styling
        enableSmallCaps: true
        hangingPunctuation: true
        opticallyAlignLetters: true

  # Appended to the preview text if enabled.
  previewPad:
    '&#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;'
