# Default HTML build configuration
htmlBuild:
  options:
    dev:
      validationLevel: 'strict'
      beautify: true
    prod:
      validationLevel: 'strict'
      beautify: false
      minify: true
      keepComments: false
