# Default HTML build configuration
htmlBuild:
  options:
    validationLevel: 'strict'
    beautify: true # Production changes to false
    # Production adds:
    # minify: true
    # keepComments: false
