# Default HTML build configuration
htmlBuild:
  options:
    validationLevel: 'strict'
    fileExt: config.user.files.templateExt
    beautify: true # Production changes to false
    # Production adds:
    # minify: true
    # keepComments: false
