# Notification messages displayed at various points in the build.
# Bodies are required; titles are optional.
messages:
  completeHandlebars:
    body: 'Handlebars processing complete'
  completeMJML:
    body: 'MJML processing complete'
  completeTypography:
    body: 'Typographical enhancements performed with Typeset'
  productionBuild:
    title: 'Production:'
    body: 'Minified with HTML comments stripped'
  templateMissing:
    title: 'Main template file cannot be found'
    body: 'Check the filename specified in your `config.yaml` file.'
  multipleWebFonts:
    title: 'Multiple web fonts enabled:'
    body: 'You have enabled both a Google web font and a custom web font. MJML will only render the first provided web font.'
