# Default plain-text build configuration
textBuild:
  options:
    selectors:
      - # Skip mobile navigation container
        selector: 'div.mj-menu-trigger'
        format: 'skip'
    tables: true
    tags:
      img:
        format: 'skip'
  include:
    images: false
    partials:
      topNav: true
      banner: true
      salutation: true
      body: true
      signoff: true
      social: true
      bottomNav: true
      footer: true
