# Validation rules
validationRules:
  - type: ascii
    file: config.yaml
    selectors:
      - config.user.folders
      - config.user.files
      - config.user.language
  - type: size
    file: themeConfig.yaml
    selectors:
      - config.theme.sections.main.horizontalPadding
      - config.theme.sections.salutation.padding
      - config.theme.sections.body.padding
      - config.theme.sections.signoff.padding
      - config.theme.sections.social.horizontalPadding
      - config.theme.sections.social.verticalPadding
      - config.theme.sections.social.topBorder.verticalPadding
      - config.theme.sections.social.topBorder.borderWidth
      - config.theme.sections.footer.horizontalPadding
      - config.theme.sections.footer.verticalPadding
      - config.theme.text.default.size
      - config.theme.text.default.verticalPadding
  - type: oneOf
    file: themeConfig.yaml
    selectors:
      - config.theme.fonts.stack.base
    opt:
      - sans
      - serif
      - mono
  - type: url
    file: themeConfig.yaml
    selectors:
      - config.theme.fonts.stack.custom.href
