# Validation rules
# Available types:
# - ascii (checks that string has only ASCII characters)
# - size (checks that string has 'px' and no other CSS length unit)
# - oneOf (checks that string is in provided 'opt' array of strings)
# - url (checks that string is a valid URL and double-quoted)
validationRules:
  - type: ascii
    selectors:
      - config.user.folders
      - config.user.files
      - config.user.language
  - type: size
    selectors:
      - config.theme.sections.main.horizontalPadding
      - config.theme.sections.salutation.padding
      - config.theme.sections.body.padding
      - config.theme.sections.signoff.padding
      - config.theme.sections.social.horizontalPadding
      - config.theme.sections.social.verticalPadding
      - config.theme.sections.social.topBorder.verticalPadding
      - config.theme.sections.social.topBorder.borderWidth
      - config.theme.sections.footer.horizontalPadding
      - config.theme.sections.footer.verticalPadding
      - config.theme.text.default.size
      - config.theme.text.default.verticalPadding
      - config.theme.buttons.primary.height
      - config.theme.buttons.primary.width
      - config.theme.buttons.primary.buttonPadding
      - config.theme.buttons.primary.contentPadding
      - config.theme.buttons.primary.cornerRadius
      - config.theme.buttons.primary.textSize
      - config.theme.buttons.secondary.height
      - config.theme.buttons.secondary.width
      - config.theme.buttons.secondary.buttonPadding
      - config.theme.buttons.secondary.contentPadding
      - config.theme.buttons.secondary.cornerRadius
      - config.theme.buttons.secondary.textSize
      - config.theme.buttons.ghost.height
      - config.theme.buttons.ghost.width
      - config.theme.buttons.ghost.buttonPadding
      - config.theme.buttons.ghost.contentPadding
      - config.theme.buttons.ghost.cornerRadius
      - config.theme.buttons.ghost.borderWidth
      - config.theme.buttons.ghost.textSize
  - type: oneOf
    selectors:
      - config.theme.fonts.stack.base
    opt:
      - sans
      - serif
      - mono
  - type: url
    selectors:
      - config.theme.page.backgroundImage
      - config.theme.fonts.stack.custom.href
