# Notification messages displayed at various points in the build.
# Bodies are required; titles are optional.
messages:
  cleaning:
    body: 'Removing generated files...'
  completeHandlebars:
    body: 'Handlebars processing finished.'
  completeMJML:
    body: 'MJML processing finished.'
  voidTags:
    body:
      'Self-closing (singleton) elements like <br /> and <hr /> are invalid in
      MJML (use tags like <mj-spacer> and <mj-divider> instead) and may generate
      errors. Self-closing MJML tags like <mj-image src="a.jpg" /> can create
      problems with HTML parsers. Instead, use a closing tag like this:
      <mj-image src="a.jpg"></mj-image>'
  productionBuild:
    title: 'Production:'
    body: 'Minified with HTML comments stripped.'
  templateMissing:
    title: 'Main template file cannot be found'
    body: 'Check the filename specified in your `config.yaml` file.'
  multipleWebFonts:
    title: 'Multiple web fonts enabled:'
    body:
      'You have enabled both a Google web font and a custom web font. MJML will
      only render the first provided web font.'
  plaintextOff:
    title: 'Plain-text generation turned off.'
    body: 'Plain-text version will not be generated.'
