#
# THEME CONFIGURATION
#
# Settings here affect the theme within this design's directory only.
#
# Color values:
# Quote all values to account for pound signs. Use hex (3- or 6-digits; MJML
# will render it in 6 digits) or RGB formats. Do not use RGBA values or CSS
# color keywords, as these are not universally supported. Also note that some
# email clients will attempt to invert colors when the user has set a preference
# for dark mode. You have limited control over what these inverted colors will
# be, though workarounds exist. Resources:
# https://www.litmus.com/blog/background-colors-html-email/
# https://www.hteumeuleu.com/2021/fixing-gmail-dark-mode-css-blend-modes/
#
# Font sizes:
# Set in pixels. Email clients render ems at vastly different sizes; 1em can
# vary from as small as 12px to as large as 17px. Resources:
# https://us4.campaign-archive.com/?u=00194e641f365c79871912856&id=1b0c8bc3ba&e=d274356b59
# https://email.uplers.com/blog/em-or-px-how-to-code-your-emails-right/

# Colors
# See "Color values" at the top of this document.
colors:
  # primary: Used for buttons, navigation menus, and social media icons.
  primary: '#800080'

# Fonts
fonts:
  default:
    # size: See "Font sizes" at the top of this document.
    size: 18px
    # color: See "Color values" at the top of this document.
    color: '#666'
  stack:
    # Base options:
    #   'sans'
    #   'serif'
    #   'mono'
    #
    # Sets a base font stack of safe fonts (sans-serif, serif, or monospaced,
    # respectively), for every OS and device. These will look
    # similar, though not identical, across email systems. For more information
    # about this approach, see:
    # https://markdotto.com/2018/02/07/github-system-fonts/#the-stack
    # https://www.digitalocean.com/community/tutorials/css-system-font-stack
    # https://css-tricks.com/snippets/css/system-font-stack/
    # https://systemfontstack.com
    #
    # If you don't enable 'google' or 'custom', below, these will be the only
    # fonts used.
    base: sans

    google:
      # google: If enabled, choose a Google font and options, and this will
      # automatically embed the font in a best-practice tag. Note that web fonts
      # require an additional download (potentially slowing down loading) and
      # are only visible in a small number of email systems, so most people will
      # be seeing the base font set above. For more information about this
      # approach, see:
      # https://www.litmus.com/blog/the-ultimate-guide-to-web-fonts/
      # https://css-tricks.com/kinda-can-use-custom-fonts-html-emails/
      enabled: true

      # The name of the Google Font. Capitalization and spaces count!
      name: Source Sans Pro

      # The font weight(s) you want to use (enter in ascending order):
      weights:
        - 400
        - 900

      # Whether to include an italic variant for each weight
      italics: true

    custom:
      # custom: If enabled, choose a non-Google web font, or use an
      # already-crafted URI pointing to a font-loading CSS file.
      enabled: false

      # The name of your custom font
      name: Example Custom Font

      # Valid URI pointing to a CSS file that loads web font(s). For an example,
      # here's Google Fonts' file for Sans Serif Pro:
      # https://fonts.googleapis.com/css2?family=Source+Sans+Pro&amp;display=swap
      # You'll probably want to include references to bold and italics variants
      # as well.
      href: https://example.com/font.css
