#
# THEME CONFIGURATION
#
# Settings here affect the theme within this design's directory only.
#

# SYNTAX NOTES
#
# Values that include CSS-reserved selectors such as periods, commas, slashes or
# colons will error unless they are quoted twice, "'Like this.'" An example is
# the custom font URL.
#
# Any values that include the pound sign (#), such as hexidecimal color values,
# need to be single-quoted, '#Likethis'.
#
# Color values:
# Use CSS color keywords, RGB format, or hex format. You can use either 3- or
# 6-digit hex values; MJML will automatically convert them. Do not use RGBA.
# Also note that some email clients will attempt to invert colors when the user
# has set a preference for dark mode. You have limited control over what these
# inverted colors will be, though workarounds exist. Resources:
# https://www.litmus.com/blog/background-colors-html-email/
# https://www.hteumeuleu.com/2021/fixing-gmail-dark-mode-css-blend-modes/
#
# Font sizes:
# Set in pixels. Email clients render ems at vastly different sizes; 1em can
# vary from as small as 12px to as large as 17px. Resources:
# https://us4.campaign-archive.com/?u=00194e641f365c79871912856&id=1b0c8bc3ba&e=d274356b59
# https://email.uplers.com/blog/em-or-px-how-to-code-your-emails-right/

# COLOR BRANDING
# See "Color values" at the top of this document.
colors:
  # primary: Color for buttons, navigation menus, and social media icons.
  primary: '#800080'
  # secondary: Color for headline text.
  secondary: '#666f9f'

# FONT SETTINGS
fonts:
  stack:
    # Base options:
    #   'sans'
    #   'serif'
    #   'mono'
    #
    # Sets a base font stack of safe fonts (sans-serif, serif, or monospaced,
    # respectively), for every OS and device. These will look
    # similar, though not identical, across email systems. For more information
    # about this approach, see:
    # https://markdotto.com/2018/02/07/github-system-fonts/#the-stack
    # https://www.digitalocean.com/community/tutorials/css-system-font-stack
    # https://css-tricks.com/snippets/css/system-font-stack/
    # https://systemfontstack.com
    #
    # If you don't enable 'google' or 'custom', below, these will be the only
    # fonts used.
    base: sans

    google:
      # google: If enabled, choose a Google font and options, and this will
      # automatically embed the font in a best-practice tag. Note that web fonts
      # require an additional download (potentially slowing down loading) and
      # are only visible in a small number of email systems, so most people will
      # be seeing the base font set above. For more information about this
      # approach, see:
      # https://www.litmus.com/blog/the-ultimate-guide-to-web-fonts/
      # https://css-tricks.com/kinda-can-use-custom-fonts-html-emails/
      enabled: true

      # The name of the Google Font. Capitalization and spaces count!
      name: Source Sans Pro

      # The font weight(s) you want to use (enter in ascending order):
      weights:
        - 400
        - 900

      # Whether to include an italic variant for each weight
      italics: true

    custom:
      # custom: If enabled, choose a non-Google web font, or use an
      # already-crafted URI pointing to a font-loading CSS file.
      enabled: false

      # The name of your custom font
      name: Example Custom Font
      # Valid URI pointing to a CSS file that loads web font(s). For an example,
      # here's Google Fonts' file for Sans Serif Pro:
      # https://fonts.googleapis.com/css2?family=Source+Sans+Pro&amp;display=swap
      # You'll probably want to include references to bold and italics variants
      # as well.
      href: "'https://example.com/font.css'"

# TEXT STYLES
text:
  # default: Styles for body text, when not otherwise styled.
  default:
    # size: See "Font sizes" at the top of this document.
    size: 18px
    # color: See "Color values" at the top of this document.
    color: '#666'
    # line-height: As in CSS, set to unitless values that multiply the font
    # size. For instance, if your default font size is 18px, a line-height of
    # 1 would set it to 18px as well; a setting of 1.5 would set it to 27px.
    line-height: 2
  # links: Color for links within text. This does not affect the link color in
  # buttons or navigation items.
  # links: '#800080'
  # # email-bg: Background color for the overall email. Note that some email
  # # clients will override this with white.
  # email-bg: white
  # # container-bg: Background color for the content container.
  # container-bg: purple
  # # text: Default color for text unless overridden on particular kinds of text.
  # text: '#666f9f'
