name: Alex inclusive writing check
# https://alexjs.com

on: pull_request_target

jobs:
  alex:
    name: Verify inclusive writing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Comment on new PR
        uses: brown-ccv/alex-recommends@v1.2.1
        with:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          message_id: 'alex'
          profanity_sureness: 2
