name: Release - Generate updated changelog

on:
  push:
    tags:
      - v*

jobs:
  changelog:
    name: Update changelog for release
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        env:
          GITHUB_REF: $
        run: |
          export CURRENT_VERSION=${GITHUB_TAG/refs\/tags\/v/}
          echo "::set-env name=CURRENT_VERSION::$CURRENT_VERSION"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Update changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: $
          issues: true
          issuesWoLabels: false
          pullRequests: true
          prWoLabels: false
          unreleased: true
          header: '# Premail Changelog'
          configureSections:
            '{"features":{"prefix":"**New features:**","labels":["Type:
            Feature"]},"security":{"prefix":"**Security
            patches:**","labels":["Type: Security"]},"bugs":{"prefix":"**Bug
            fixes:**","labels":["Type:
            Bug"]},"docs":{"prefix":"**Documentation:**","labels":["Type:
            Documentation"]},"other":{"prefix":"**Other
            updates:**","labels":["Type: Build","Type: Dependencies","Type:
            Chore"]}}'
          excludeLabels: '"Type: Question","Status: wontfix"'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update changelog for tag $
          file_pattern: CHANGELOG.md

  release_notes:
    name: Create release notes
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Get version from tag
        env:
          GITHUB_REF: $
        run: |
          export CURRENT_VERSION=${GITHUB_TAG/refs\/tags\/v/}
          echo "::set-env name=CURRENT_VERSION::$CURRENT_VERSION"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Get changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: $
          path: ./CHANGELOG.md

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: $
        with:
          tag_name: $
          release_name: Release $
          body: $
          draft: false
          prerelease: false
