name: Release - Generate updated changelog
# Sourced from:
# https://web.archive.org/web/20210307025139/https://renehernandez.io/essays/2020/09/23/automate-changelog-and-releases-creation-in-github/

on:
  push:
    tags:
      - v*

jobs:
  changelog:
    name: Update changelog for release
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        env:
          GITHUB_REF: $
        run: |
          export CURRENT_VERSION=${GITHUB_TAG/refs\/tags\/v/}
          echo "::set-env name=CURRENT_VERSION::$CURRENT_VERSION"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Update changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: $
          author: false
          issues: true
          issuesWoLabels: false
          pullRequests: true
          prWoLabels: false
          unreleased: false
          headerLabel: '# Premail Changelog'
          configureSections:
            '{"features":{"prefix":"### New features","labels":["Type:
            Feature"]},"security":{"prefix":"### Security
            patches","labels":["Type: Security"]},"bugs":{"prefix":"### Bug
            fixes","labels":["Type: Bug"]},"docs":{"prefix":"###
            Documentation","labels":["Type:
            Documentation"]},"other":{"prefix":"### Other
            updates","labels":["Type: Build","Type: Dependencies","Type:
            Chore"]}}'
          excludeLabels: 'Type: Question,Status: wontfix,x-Bot: No Changelog'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update changelog for tag $
          file_pattern: CHANGELOG.md

  copy_changelog:
    needs: changelog
    name: Copy changelog to documentation site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy files
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'CHANGELOG.md'
          destination_repo: 'premail/website'
          destination_branch: 'main'
          destination_folder: 'src/pages'
          user_email: 'git@rootwork.org'
          user_name: 'rootwork'
          commit_message: '[bot] Updated changelog'

  release_notes:
    name: Create release notes
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Get version from tag
        env:
          GITHUB_REF: $
        run: |
          export CURRENT_VERSION=${GITHUB_TAG/refs\/tags\/v/}
          echo "::set-env name=CURRENT_VERSION::$CURRENT_VERSION"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Get changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: $
          path: ./CHANGELOG.md

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: $
        with:
          tag_name: $
          release_name: Release $
          body: $
          draft: true
          prerelease: false
