name: Copy readme to example directory

on:
  push:
    branches:
      - '**'
    paths:
      - 'README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Copy file
        run: |
          git pull
          cp README.md ./src/example/README.md
      - name: Autocommit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: README.md changed; updating example directory
