name: Node.js CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '.github/**'

jobs:
  node:
    name: Node install and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, windows-latest]
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run package tests
        run: npm test
      - name: Initialize, build, and destroy a project
        run: |
          npm install -g .
          npm install -g gnomon
          mkdir -p project
          cd project
          premail init --debug | gnomon --medium=1.0 --high=5.0 --ignore-blank --real-time=false
          premail build | gnomon --medium=1.0 --high=5.0 --ignore-blank --real-time=false
          premail destroy --yes --debug | gnomon --medium=1.0 --high=5.0 --ignore-blank --real-time=false
