name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  node:
    name: Node install and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, windows-2019, windows-2022]
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run package tests
        run: npm test
      - name: Create a dummy project and build
        run: |
          npm install -g .
          mkdir -p project && cd project
          premail init
          premail build
          premail destroy --yes
          cd .. && rm -rf project
