name: Remove unrelated mirrored documentation

on:
  push:
    branches:
      - 'main'
      - 'v2.0.0'
    paths:
      - docs/index.js
      - docs/index.module.css

jobs:
  checkout:
    name: Check out repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  delete_1:
    name: Delete file
    uses: JesseTG/rm@v1.0.2
    with:
      path: /docs/index.js
  delete_2:
    name: Delete file
    uses: JesseTG/rm@v1.0.2
    with:
      path: /docs/index.module.css
