name: Update readme

on:
  push:
    branches:
      - '**'
    paths:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Update table of contents
        run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          ./gh-md-toc --insert --no-backup README.md
          rm ./gh-md-toc
      - name: Copy the file to the example directory
        run: |
          cp README.md ./src/example/README.md
      - name: Autocommit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated readme update
