name: Update built versions of design and example email

on:
  push:
    branches:
      - main
    paths:
      - 'src/scaffolding/project/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Globally install local Premail
        run: npm install -g .
      - name: Enter project scaffolding directory
        run: |
          cd src
          cd scaffolding
          cd project
      - name: Recompile default design
        run: premail build --noserve
      - name: Recompile example email
        run: premail build --noserve -e _example
      - name: Autocommit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated dist update
