name: Update readme

on:
  push:
    branches:
      - '**'
    paths:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install Node dependencies
        run: npm ci --ignore-scripts
      - name: Update help output
        run: |
          npm install premail
          npm run readme
      - name: Generate sponsors
        uses: JamesIves/github-sponsors-readme-action@1.0.5
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
      - name: Update table of contents
        run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          ./gh-md-toc --insert --no-backup README.md
          rm ./gh-md-toc
      - name: Copy the file to the example directory
        run: |
          cp README.md ./src/example/README.md
      - name: Autocommit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated readme update
